security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: 'argon2i'
            memory_cost: 1024
            time_cost: 2
            threads: 2
        App\Entity\User:
            algorithm: argon2i

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:       /api/login_check
                success_handler:  lexik_jwt_authentication.handler.authentication_success
                failure_handler:  lexik_jwt_authentication.handler.authentication_failure
        help:
            pattern:   ^/api/5766d45bdba1152105abfd9662e55140
            security: false
        api:
            pattern:   ^/api
            stateless: true
            anonymous: false
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
