INSERT INTO `tbl_relationship` (`id_space`, `title`)
VALUES (1, 'Accountant'),
       (1, 'ALWP'),
       (1, 'Attorney'),
       (1, 'Attorney-In-Fact'),
       (1, 'Brother'),
       (1, 'Brother POA'),
       (1, 'Brother-in-Law'),
       (1, 'Caregiver'),
       (1, 'Caretaker'),
       (1, 'Case Manager'),
       (1, 'Conservator'),
       (1, 'Cousin'),
       (1, 'Daughter'),
       (1, 'Daughter POA'),
       (1, 'Daughter-in-Law'),
       (1, 'Designated POA'),
       (1, 'Doctor'),
       (1, 'Durable POA'),
       (1, 'Father'),
       (1, 'Fiduciary'),
       (1, 'Financial POA'),
       (1, 'Foster Daughter'),
       (1, 'Friend'),
       (1, 'Friend POA'),
       (1, 'Grand Daughter'),
       (1, 'Grand Niece'),
       (1, 'Grand Son'),
       (1, 'Great Nephew'),
       (1, 'Guardian'),
       (1, 'Husband'),
       (1, 'Mother'),
       (1, 'Neighbor'),
       (1, 'Nephew'),
       (1, 'Nephew POA'),
       (1, 'Nephew-in-Law'),
       (1, 'Niece'),
       (1, 'Niece-in-Law'),
       (1, 'Payee'),
       (1, 'Public Guardian'),
       (1, 'Relative'),
       (1, 'Significant Other'),
       (1, 'Sister'),
       (1, 'Sister POA'),
       (1, 'Sister-in-Law'),
       (1, 'Son'),
       (1, 'Son Health POA'),
       (1, 'Son POA'),
       (1, 'Son POA Trustee'),
       (1, 'Son-in-Law'),
       (1, 'Spouse'),
       (1, 'SSC'),
       (1, 'Step Daughter'),
       (1, 'Step Father'),
       (1, 'Step Son'),
       (1, 'Trust Office'),
       (1, 'Trustee'),
       (1, 'Unknown'),
       (1, 'Wife');
