INSERT INTO `tbl_medical_history_condition` (`id_space`, `title`)
VALUES (1, 'Acetylsalicylic Acid'),
       (1, 'Alcohol Abuse'),
       (1, 'Alcohol Dependence'),
       (1, 'Aneurysm'),
       (1, 'Ataxia'),
       (1, 'Atrial Fibrilation'),
       (1, 'Cancer, Bladder'),
       (1, 'Cancer, Breast'),
       (1, 'Cancer, Skin'),
       (1, 'Cancer, Thyroid'),
       (1, 'Catheter'),
       (1, 'CCB d/t 3AV Block'),
       (1, 'Celebrovascular'),
       (1, 'Cellulitis'),
       (1, 'Cerebrovascular Disease'),
       (1, 'Cancer, Cervical'),
       (1, 'Cholecystitis'),
       (1, 'Chrons Disease'),
       (1, 'Cognitive disorder NOS'),
       (1, 'Cancer, Colon'),
       (1, 'Cronic Kidney Disease'),
       (1, 'CVD'),
       (1, 'Dementia, Early'),
       (1, 'Dementia, Severe'),
       (1, 'Dementia, Vascular '),
       (1, 'Dementia'),
       (1, 'Depression'),
       (1, 'Diabetic Neuropathy'),
       (1, 'Emphysema'),
       (1, 'Esophageal Ulcer'),
       (1, 'Femur Hintertrochanteric fracture'),
       (1, 'Focal Status Epilepticus'),
       (1, 'Fracture, Femoral Neck'),
       (1, 'Fracture, Femur'),
       (1, 'Fracture, Hip'),
       (1, 'Fracture, Left Humor'),
       (1, 'Fracture, Lumbar'),
       (1, 'Fracture, Patillar'),
       (1, 'Fracture, Ribs'),
       (1, 'Fractures, Compression'),
       (1, 'Hearing Loss'),
       (1, 'Hemiparesis'),
       (1, 'Hemiplegia'),
       (1, 'Hip Surgery'),
       (1, 'HX Brain Tumor'),
       (1, 'HX Lung Cancer'),
       (1, 'HX of Suicide Attempts'),
       (1, 'HX of Transient Ischemic Attacks'),
       (1, 'Hyponatemia'),
       (1, 'Hypothyroid'),
       (1, 'Hypoxemia'),
       (1, 'IBS'),
       (1, 'Insomnia'),
       (1, 'Large area brain bleed'),
       (1, 'Leg Weakness'),
       (1, 'Lumbar Stenosis'),
       (1, 'Migraines'),
       (1, 'Nail Fungus'),
       (1, 'Neuropathy'),
       (1, 'Osteoporosis'),
       (1, 'Pneumonia'),
       (1, 'Cancer, Prostate'),
       (1, 'Psoriasis'),
       (1, 'Reflux Disease'),
       (1, 'Respitory failure'),
       (1, 'S/P Arrest'),
       (1, 'S/P Back Surgery'),
       (1, 'S/P Bilateral Humerus Fracture'),
       (1, 'S/P Hip Fracture'),
       (1, 'S/P Hysterectomy'),
       (1, 'S/P PEA Arrest'),
       (1, 'Seizures'),
       (1, 'Stroke'),
       (1, 'Subdural Hematoma'),
       (1, 'Tinea Pedis'),
       (1, 'Unspecified Hypothyroidism'),
       (1, 'Urinary Tract Incontinence'),
       (1, 'Urinary Tract Infection'),
       (1, 'Vision Loss');
