INSERT INTO `tbl_speciality` (`id_space`, `title`)
VALUES (1, 'Allergy and Immunology'),
       (1, 'Anesthesiology'),
       (1, 'Dermatology'),
       (1, 'Diagnostic Radiology'),
       (1, 'Emergency Medicine'),
       (1, 'Family Medicine'),
       (1, 'Internal Medicine'),
       (1, 'Endocrinology'),
       (1, 'Gastroenterology'),
       (1, 'Geratiric Medicine'),
       (1, 'Hematology'),
       (1, 'Interventional Cardiology'),
       (1, 'Medical Oncology'),
       (1, 'Nephrology'),
       (1, 'Rheumatology'),
       (1, 'Medical Genetics'),
       (1, 'Neurology'),
       (1, 'Nuclear Medicine'),
       (1, 'Obstetrics and Gynecology'),
       (1, 'Ophthalmology'),
       (1, 'Orthopaedic Surgery'),
       (1, 'Otolaryngology - Head and Neck Surgery'),
       (1, 'Pathology'),
       (1, 'Physical Medicine and Rehabilitation'),
       (1, 'Plastic Surgery'),
       (1, 'Preventive Medicine'),
       (1, 'Psychiatry'),
       (1, 'Radiology'),
       (1, 'Surgery'),
       (1, 'Thoracic Surgery'),
       (1, 'Urology');
